import { 
    ApplicationCommandOptionType, 
    ChannelType, 
    MessageFlags 
} from "discord.js";

import { Subcommand } from "../../../structures/Subcommand";

export default new Subcommand({
    name: 'update',
    description: 'Updates channel that is linked to a webhook (identified by uuid)',
    options: [
        {
            name: 'uuid',
            description: 'UUID associated with a webhook generated by /create',
            type: ApplicationCommandOptionType.String,
            required: true
        },
        {
            name: 'channel',
            description: 'Channel to post discount events on',
            type: ApplicationCommandOptionType.Channel,
            channel_types: [ChannelType.GuildText],
            required: true
        }
    ],
    run: async ({ interaction }) => {
        await interaction.reply({ content: `Updated Webhook for channel ${ interaction.options.get('channel')?.value }`, flags: MessageFlags.Ephemeral })
    }            
})